name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ["18.x", "20.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Confirm Node version
        run: node --version
      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
      - name: Run lint
        run: npm run lint
